@Library('Shared') _
pipeline {
    agent any
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/shubhs11patil/Wanderlust-Mega-Project.git", "main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -E 's|wanderlust-backend[^:]*:[^"]*|wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}|' backend.yaml
                            sed -i -E 's|wanderlust-frontend[^:]*:[^"]*|wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}|' frontend.yaml
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                            echo "Checking repository status:"
                            git status
                            
                            echo "Adding changes to git:"
                            git add .

                            echo "Checking for changes before commit..."
                            if ! git diff-index --quiet HEAD --; then
                                echo "Committing changes..."
                                git commit -m "Updated environment variables"
                                echo "Pushing changes to GitHub..."
                                git push https://github.com/shubhs11patil/Wanderlust-Mega-Project.git main
                            else
                                echo "No changes to commit."
                            fi
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                from: 'shubhamlokhande11997@gmail.com',
                subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px;">
                            <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px;">
                            <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px;">
                            <p><strong>Build URL:</strong> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'shubhamlokhande11997@gmail.com',
                mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                from: 'shubhamlokhande11997@gmail.com',
                subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px;">
                            <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px;">
                            <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'shubhamlokhande11997@gmail.com',
                mimeType: 'text/html'
            }
        }
    }
}
